"""Pull Zillow ZHVI (home values) and ZORI (rents) for Atlanta metro and
compute EQ 4 trailing appreciation estimate for each.

Metro Level.

NOTE: this script previously fetched only the ZORI series (rents) while its
docstring, variable names (ZHVI_URL) and CLI both claimed to be pulling
ZHVI (home values). That mismatch meant the already-checked-in
atlanta_zillow_zhvi.csv could never actually be regenerated by running this
script -- it must have been produced some other way. Fixed by pulling both
series explicitly, each into its own correctly-labeled output file. Exact
URLs could not be re-verified against zillow.com/research/data from this
sandbox (network egress to non-GitHub hosts is blocked here); confirm they
still resolve before relying on a fresh pull.
"""
import argparse
import pandas as pd

ZHVI_URL = (
    "https://files.zillowstatic.com/research/public_csvs/zhvi/"
    "Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv"
)
ZORI_URL = (
    "https://files.zillowstatic.com/research/public_csvs/zori/"
    "Metro_zori_uc_sfrcondomfr_sm_month.csv"
)

METRO_NAME = "Atlanta, GA"

def pull_series(url: str) -> pd.Series:
    wide = pd.read_csv(url)
    row = wide[wide["RegionName"] == METRO_NAME]
    # everything after the metadata columns is a monthly date column
    date_cols = [c for c in wide.columns if c[:2] in ("19", "20")]
    series = row[date_cols].iloc[0]
    series.index = pd.to_datetime(series.index)
    return series.astype(float).sort_index()

def compute_trailing_appreciation(hpi: pd.Series, alpha: float) -> pd.DataFrame:
    df = hpi.rename("hpi").to_frame()
    df["trail_1_3"] = df["hpi"].shift(1) + df["hpi"].shift(2) + df["hpi"].shift(3)
    df["trail_13_15"] = (
        df["hpi"].shift(13) + df["hpi"].shift(14) + df["hpi"].shift(15)
    )
    df["g"] = alpha * (df["trail_1_3"] / df["trail_13_15"] - 1)
    return df.dropna(subset=["g"])
 
 
def pull_and_write(url: str, alpha: float, start: str, out_name: str):
    hpi = pull_series(url)
    df = compute_trailing_appreciation(hpi, alpha)
    df = df[df.index >= start]

    df.to_csv(out_name, index_label="date")
    print(f"Wrote {len(df)} monthly obs to {out_name}")
    print(df[["hpi", "g"]].tail(12))

    print("\nMonthly g stats, full window:")
    print(df["g"].describe())

    print("\n2020-2023 window (for comparison against Case-Shiller pull):")
    val = df[(df.index >= "2020-01-01") & (df.index <= "2023-12-31")]
    print(val["g"].describe())
    val.to_csv(out_name.replace(".csv", "_2020_2023.csv"), index_label="date")
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--alpha", type=float, default=1.0, help="Eq (4) alpha, placeholder until calibrated"
    )
    ap.add_argument(
        "--start", default="2015-01-01", help="trim start date for the output window"
    )
    args = ap.parse_args()

    print("=== ZHVI (home values) ===")
    pull_and_write(ZHVI_URL, args.alpha, args.start, "atlanta_zillow_zhvi.csv")

    print("\n=== ZORI (rents) ===")
    pull_and_write(ZORI_URL, args.alpha, args.start, "atlanta_zillow_zori.csv")


if __name__ == "__main__":
    main()